version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crm-network

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: crm
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: 3fa85f64d97986e6c450a00dff5a8c31e99bc373a0e28b2e52a6458a75cfbb6d
    command: npm start
    networks:
      - crm-network

volumes:
  pgdata:

networks:
  crm-network:
